SUPABASE_URL = 'https://hrfqvipwxuqssnnwowno.supabase.co'
SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZnF2aXB3eHVxc3Nubndvd25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxODI3NjAsImV4cCI6MjA4Mzc1ODc2MH0.jpYbURw_lc04dEBo7J9JK5eDOuJQq-EKLMdKIT4jARM'

GEMINI_API_KEY = "AIzaSyDc9KG-b2_ogiEiPGC8AMz4wMUIwu7P_Wc"
SERPAPI_KEY = "9850b83fd97faa83c91915d6c788126273174c0217a1f2c306ad93956ae543fd"