SUPABASE_URL = 'https://hrfqvipwxuqssnnwowno.supabase.co'
SUPABASE_KEY = 'sb_publishable_Sdz_-3XX4Y05hgcBHooRPw_yufksqyO'

GEMINI_API_KEY = "AIzaSyDc9KG-b2_ogiEiPGC8AMz4wMUIwu7P_Wc"
SERPAPI_KEY = "9850b83fd97faa83c91915d6c788126273174c0217a1f2c306ad93956ae543fd"